<?php

return [
    'dictionary' => [
        'score' => [
            'A1' => [
                'code' => 'A1',
                'range' => '740 - 900',
                'range_percentage' => '0.00% - 0.78%',
                'description' => 'Risiko Sangat Rendah',
            ],
            'A2' => [
                'code' => 'A2',
                'range' => '726 - 739',
                'range_percentage' => '0.79% - 1.07%',
                'description' => 'Risiko Sangat Rendah',
            ],
            'A3' => [
                'code' => 'A3',
                'range' => '713 - 725',
                'range_percentage' => '1.08% - 1.44%',
                'description' => 'Risiko Sangat Rendah',
            ],
            'B1' => [
                'code' => 'B1',
                'range' => '701 - 712',
                'range_percentage' => '1.45% - 1.89%',
                'description' => 'Risiko Rendah',
            ],
            'B2' => [
                'code' => 'B2',
                'range' => '689 - 700',
                'range_percentage' => '1.90% - 2.48%',
                'description' => 'Risiko Rendah',
            ],
            'B3' => [
                'code' => 'B3',
                'range' => '677 - 688',
                'range_percentage' => '2.49% - 3.25%',
                'description' => 'Risiko Rendah',
            ],
            'C1' => [
                'code' => 'C1',
                'range' => '665 - 676',
                'range_percentage' => '3.26% - 4.24%',
                'description' => 'Risiko Menengah',
            ],
            'C2' => [
                '',
                'code' => 'C2',
                'range' => '653 - 664',
                'range_percentage' => '4.25% - 5.52%',
                'description' => 'Risiko Menengah',
            ],
            'C3' => [
                'code' => 'C3',
                'range' => '641 - 652',
                'range_percentage' => '5.53% - 7.15%',
                'description' => 'Risiko Menengah',
            ],
            'D1' => [
                'code' => 'D1',
                'range' => '620 - 640',
                'range_percentage' => '7.16% - 11.12%',
                'description' => 'Risiko Tinggi',
            ],
            'D2' => [
                '',	'604 - 619',	'11.13% - 15.32%',	'Risiko Tinggi',
                'code' => 'D2',
                'range' => '604 - 619',
                'range_percentage' => '11.13% - 15.32%',
                'description' => 'Risiko Tinggi',
            ],
            'D3' => [
                'code' => 'D3',
                'range' => '574 - 603',
                'range_percentage' => '15.33% - 26.57%',
                'description' => 'Risiko Tinggi',
            ],
            'E1`' => [
                '',	'530 - 573',	'26.58% - 50.00%',	'Risiko Sangat Tinggi',
                'code' => 'E1',
                'range' => '530 - 573',
                'range_percentage' => '26.58% - 50.00%',
                'description' => 'Risiko Sangat Tinggi',
            ],
            'E2' => [
                'code' => 'E2',
                'range' => '251 - 529',
                'range_percentage' => '50.01% - 99.99%',
                'description' => 'Risiko Sangat Tinggi',
            ],
            'E3' => [
                'code' => 'E3',
                'range' => '250',
                'range_percentage' => '100.00%',
                'description' => 'Risiko Sangat Tinggi',
            ],

        ],
        'facility' => [
            'type' => [
                'Installment' => 'Fasilitas yang mencakup pencicilan',
                'NonInstallment' => 'Fasilitas tanpa pencicilan',
                'CreditCard' =>	'Fasilitas kartu kredit',
                'RevolvingCredit' => 'Fasilitas kredit bergulir',
                'Invoice' => 'Fasilitas penagihan',
                'BankGuarantee' => 'Bank garansi',
                'Other' => 'Garansi lainnya',
                'CoFinancing' => 'Fasilitas Dalam rangka pembiayaan bersama dengan kreditor lain (sindikasi)',
                'LoanRestructuring' => 'Fasilitas Dalam rangka restrukturisasi kredit',
                'ChannelingLoan' =>	'Fasilitas Penyaluran kredit melalui lembaga lain (channeling)',
                'CreditTakeover' =>	'Pengambilalihan kredit',
                'Securities' =>	'Surat berharga dengan Note Purchase Agreement (NPA)',
                'Musyarakah' =>	'Fasilitas pembiayaan musyarakah',
                'Mudharabah' =>	'Fasilitas pembiayaan mudharabah',
                'Murabahah' => 'Fasilitas piutang murabahah',
                'Salam' => 'Fasilitas piutang salam',
                'Istishna' => 'Fasilitas piutang istishna',
                'OtherWithLoanAgreement' =>	'Fasilitas lain-lain yang mengandung perjanjian kredit (PK)',
                'CheckingAccount' => 'Fasilitas giro bersaldo debet',
                'TradeReceivables' => 'Tagihan atas transaksi perdagangan',
                'OtherWithoutLoanAgreement' => 'Fasilitas lain-lain tanpa perjanjian kredit (PK) ',
                'KUKExtractedFromBI' =>	'Fasilitas kredit usaha kecil dalam rangka penerusan kredit dari BI',
                'KUKOther' => 'Fasilitas kredit usaha kecil Lainnya',
                'ManagedCredit' => 'Fasilitas Bukan KUK - Kredit Kelolaan',
                'NonKUKExtractedFromBI' => 'Fasilitas Bukan KUK - Dalam rangka penerusan kredit dari BI',
                'ProjectAssistance' => 'Fasilitas Bukan KUK - Bantuan proyek',
                'MudharabahMuqayyadah' => 'Fasilitas Mudharabah Muqayaddah',
                'IrrevocableForeignLC' => 'Fasilitas LC irrevocable - luar negeri',
                'IrrevocableDomesticLC' => 'Fasilitas LC irrevocable - dalam negeri',
                'ShippingGuarantee' => 'Fasilitas garansi pengiriman',
                'RiskSharing' => 'Fasilitas Risk Sharing',
                'StandbyLC' => 'Fasilitas Standby LC',
                'Endorsement' => 'Endosemen atas surat berharga',
                'RevocableForeignLC' =>	'Fasilitas LC revocable - luar negeri',
                'RevocableDomesticLC' => 'Fasilitas LC revocable - dalam negeri',
            ],
            'status' => [
                'GrantedButNotActivated' => 'Fasilitas sudah disetujui namun belum diaktifkan',
                'GrantedAndActivated' => 'Fasilitas sudah disetujui dan diaktifkan',
                'Rescheduled' => 'Fasilitas dijadwal ulang perihal persetujuan / pencairannya',
                'WrittenOff' => 'Fasilitas dihapuskan',
                'Prolonged' => 'Fasilitas diperpanjang',
                'Restructured' => 'Fasilitas telah direstrukturisasi',
                'ChargesRemoved' => 'Fasilitas hapus tagihannya',
                'BoughtFromIBRAPPA' => 'Fasilitas dibeli dari BPPN/PPA',
                'RestructuredByIBRAPPA' => 'Fasilitas Telah direstrukturisasi oleh BPPN/PPA',
                'RestructuredNotByIBRAPPA' => 'Fasilitas Direstrukturisasi oleh lembaga pemerintah selain BPPN/PPA',
                'UnprocessedByIBRAPPA' => 'Fasilitas Belum diproses oleh BPPN/PPA',
                'SecuritizedOriginatorServicer' => 'Fasilitas Disekuritisasi (Kreditur Asal sebagai Servicer)',
                'SecuritizedOriginatorNotServicer' => 'Fasilitas Disekuritisasi (Kreditur Asal tidak sebagai Servicer)',
                'SettledOnTime' => 'Fasilitas telah dilunasi tepat waktu',
                'SettledInAdvance' => 'Fasilitas telah dilunasi sebelum waktunya',
                'SettledLate' => 'Fasilitas telah dilunasi dengan terlambat',
                'Cancelled' => 'Fasilitas dibatalkan',
                'SoldToThirdParty' => 'Fasilitas dijual ke pihak lain',
                'WrittenOff' => 'Fasilitas dihapuskan',
                'Closed' => 'Fasilitas ditutup',
                'Settled' => 'Fasilitas telah dilunasi',
                'SettledWithDiscount' => 'Fasilitas telah dilunasi dengan potongan pembayaran',
                'SubmittedToAMUPPA' => 'Fasilitas telah diserahkan ke AMU/PPA',
                'SubmittedToBUPLN' => 'Fasilitas telah diserahkan ke BUPLN',
                'PromissoryNotesSoldPaidOff' => 'Fasilitas yang Promesnya Dijual (LUNAS)',
                'PromissoryNotesSoldNotPaidOff' => 'Fasilitas yang Promesnya dijual (Belum Lunas)',
                'ConvertedIntoInvestments' => 'Fasilitas telah dikonversikan menjadi penyertaan',
                'FullyPaidCollateralExecution' => 'Fasilitas telah dilunasi dengan cara eksekusi jaminan',
                'FullyPaidResolvedThroughCourt' => 'Fasilitas telah dilunasi melalui kasus perdata di pengadilan',
                'TransferredToOtherReportingInst' => 'Fasilitas ditransfer ke institusi keuangan lain',
                'TransferredToOtherFacilities' => 'Fasilitas ditransfer ke fasilitas lain',
                'SoldByIBRAPPAToNonBank' => 'Fasilitas dijual BPPN/PPA kepada pihak Non-bank',
                'SoldToOtherNonReportingInst' => 'Fasilitas dijual ke institusi non-keuangan lain',
            ],
        ],
    ],
];
